"""Add email to vault.user

Revision ID: 02f1d5d2c1a9
Revises: 4eb105e6879b
Create Date: 2025-03-09 17:47:06.692403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02f1d5d2c1a9'
down_revision: Union[str, None] = '4eb105e6879b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True), schema='vault')
    op.create_index(op.f('ix_vault_users_email'), 'users', ['email'], unique=True, schema='vault')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_users_email'), table_name='users', schema='vault')
    op.drop_column('users', 'email', schema='vault')
    # ### end Alembic commands ###
