"""add virtual paralegal and profile picture models

Revision ID: 1c94e5cda518
Revises: 980595f77556
Create Date: 2025-04-22 08:48:48.971849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c94e5cda518'
down_revision: Union[str, None] = '980595f77556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add gender column and make email nullable in virtual_paralegals
    op.add_column('virtual_paralegals', 
        sa.Column('gender', sa.String(), nullable=True),
        schema='public'
    )
    op.alter_column('virtual_paralegals', 'email',
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema='public'
    )

    # Create vp_profile_pictures table
    op.create_table('vp_profile_pictures',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('bucket_id', sa.String(), nullable=False),
        sa.Column('path', sa.String(), nullable=False),
        sa.Column('virtual_paralegal_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['virtual_paralegal_id'], ['public.virtual_paralegals.id'], name=op.f('fk_vp_profile_pictures_virtual_paralegal_id_virtual_paralegals')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_vp_profile_pictures')),
        sa.UniqueConstraint('virtual_paralegal_id', name=op.f('uq_vp_profile_pictures_virtual_paralegal_id')),
        schema='public'
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE public.virtual_paralegals SET email = '' WHERE email IS NULL")
    op.alter_column('virtual_paralegals', 'email',
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema='public'
    )
    op.drop_column('virtual_paralegals', 'gender', schema='public')
    op.drop_table('vp_profile_pictures', schema='public')
    # ### end Alembic commands ###
