"""Add public research-search models

Revision ID: 4eb105e6879b
Revises: 5b9ea777cdab
Create Date: 2025-03-03 13:08:51.833702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eb105e6879b'
down_revision: Union[str, None] = '5b9ea777cdab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename user table to users
    op.rename_table('user', 'users', schema='vault')
    
    # Create public_searches table
    op.create_table('public_searches',
    sa.Column('title', sa.String(), nullable=False, comment='Title of the search, initially the first query, can be edited by user'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional user-provided description of this search'),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='Whether this search is featured/highlighted in the UI'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of tags associated with this search'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who created this search'),
    sa.Column('enterprise_id', sa.UUID(), nullable=False, comment='Enterprise the user belongs to'),
    sa.Column('search_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Parameters used for this search (jurisdiction, practice area, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['vault.enterprises.id'], name=op.f('fk_public_searches_enterprise_id_enterprises')),
    sa.ForeignKeyConstraint(['user_id'], ['vault.users.id'], name=op.f('fk_public_searches_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_searches')),
    schema='vault'
    )
    op.create_index('ix_public_searches_enterprise_user', 'public_searches', ['enterprise_id', 'user_id'], unique=False, schema='vault')
    op.create_index(op.f('ix_vault_public_searches_enterprise_id'), 'public_searches', ['enterprise_id'], unique=False, schema='vault')
    op.create_index(op.f('ix_vault_public_searches_is_featured'), 'public_searches', ['is_featured'], unique=False, schema='vault')
    op.create_index(op.f('ix_vault_public_searches_title'), 'public_searches', ['title'], unique=False, schema='vault')
    op.create_index(op.f('ix_vault_public_searches_user_id'), 'public_searches', ['user_id'], unique=False, schema='vault')
    
    # Create public_search_messages table
    op.create_table('public_search_messages',
    sa.Column('search_id', sa.UUID(), nullable=False, comment='The search conversation this message belongs to'),
    sa.Column('role', sa.String(), nullable=False, comment='Role of the message sender (user/assistant)'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Message content including text and metadata'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Sequence number for ordering messages within a conversation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['search_id'], ['vault.public_searches.id'], name=op.f('fk_public_search_messages_search_id_public_searches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_search_messages')),
    schema='vault'
    )
    op.create_index('ix_public_search_messages_search_sequence', 'public_search_messages', ['search_id', 'sequence'], unique=False, schema='vault')
    op.create_index(op.f('ix_vault_public_search_messages_role'), 'public_search_messages', ['role'], unique=False, schema='vault')
    op.create_index(op.f('ix_vault_public_search_messages_search_id'), 'public_search_messages', ['search_id'], unique=False, schema='vault')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop public_search_messages table
    op.drop_index(op.f('ix_vault_public_search_messages_search_id'), table_name='public_search_messages', schema='vault')
    op.drop_index(op.f('ix_vault_public_search_messages_role'), table_name='public_search_messages', schema='vault')
    op.drop_index('ix_public_search_messages_search_sequence', table_name='public_search_messages', schema='vault')
    op.drop_table('public_search_messages', schema='vault')
    
    # Drop public_searches table
    op.drop_index(op.f('ix_vault_public_searches_user_id'), table_name='public_searches', schema='vault')
    op.drop_index(op.f('ix_vault_public_searches_title'), table_name='public_searches', schema='vault')
    op.drop_index(op.f('ix_vault_public_searches_is_featured'), table_name='public_searches', schema='vault')
    op.drop_index(op.f('ix_vault_public_searches_enterprise_id'), table_name='public_searches', schema='vault')
    op.drop_index('ix_public_searches_enterprise_user', table_name='public_searches', schema='vault')
    op.drop_table('public_searches', schema='vault')
    
    # Rename users table back to user
    op.rename_table('users', 'user', schema='vault')
    # ### end Alembic commands ###