"""create_enterprise_and_vp_tables

Revision ID: 5b9ea777cdab
Revises: d43efa3914e9
Create Date: 2025-03-02 22:03:30.904488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b9ea777cdab'
down_revision: Union[str, None] = 'd43efa3914e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('subscription_tier', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enterprises')),
    sa.UniqueConstraint('domain', name=op.f('uq_enterprises_domain')),
    schema='vault'
    )
    op.create_index(op.f('ix_vault_enterprises_name'), 'enterprises', ['name'], unique=False, schema='vault')
    
    op.create_table('virtual_paralegals',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_virtual_paralegals')),
    sa.UniqueConstraint('email', name=op.f('uq_virtual_paralegals_email')),
    schema='vault'
    )
    op.create_index(op.f('ix_vault_virtual_paralegals_first_name'), 'virtual_paralegals', ['first_name'], unique=False, schema='vault')
    op.create_index(op.f('ix_vault_virtual_paralegals_last_name'), 'virtual_paralegals', ['last_name'], unique=False, schema='vault')
    
    # Add foreign key columns to user table
    op.add_column('user', sa.Column('virtual_paralegal_id', sa.UUID(), nullable=True), schema='vault')
    op.add_column('user', sa.Column('enterprise_id', sa.UUID(), nullable=True), schema='vault')
    op.create_index(op.f('ix_vault_user_enterprise_id'), 'user', ['enterprise_id'], unique=False, schema='vault')
    op.create_index(op.f('ix_vault_user_virtual_paralegal_id'), 'user', ['virtual_paralegal_id'], unique=False, schema='vault')
    op.create_foreign_key(op.f('fk_user_enterprise_id_enterprises'), 'user', 'enterprises', ['enterprise_id'], ['id'], source_schema='vault', referent_schema='vault')
    op.create_foreign_key(op.f('fk_user_virtual_paralegal_id_virtual_paralegals'), 'user', 'virtual_paralegals', ['virtual_paralegal_id'], ['id'], source_schema='vault', referent_schema='vault')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign keys first
    op.drop_constraint(op.f('fk_user_virtual_paralegal_id_virtual_paralegals'), 'user', schema='vault', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_enterprise_id_enterprises'), 'user', schema='vault', type_='foreignkey')
    op.drop_index(op.f('ix_vault_user_virtual_paralegal_id'), table_name='user', schema='vault')
    op.drop_index(op.f('ix_vault_user_enterprise_id'), table_name='user', schema='vault')
    op.drop_column('user', 'enterprise_id', schema='vault')
    op.drop_column('user', 'virtual_paralegal_id', schema='vault')
    
    # Drop tables
    op.drop_index(op.f('ix_vault_virtual_paralegals_last_name'), table_name='virtual_paralegals', schema='vault')
    op.drop_index(op.f('ix_vault_virtual_paralegals_first_name'), table_name='virtual_paralegals', schema='vault')
    op.drop_table('virtual_paralegals', schema='vault')
    op.drop_index(op.f('ix_vault_enterprises_name'), table_name='enterprises', schema='vault')
    op.drop_table('enterprises', schema='vault')
    # ### end Alembic commands ###
