"""Create User table in vault schema

Revision ID: d43efa3914e9
Revises: 
Create Date: 2025-03-02 18:44:59.378662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd43efa3914e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth.users.id'], name=op.f('fk_user_auth_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    schema='vault'
    )
    op.create_index(op.f('ix_vault_user_auth_user_id'), 'user', ['auth_user_id'], unique=True, schema='vault')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_user_auth_user_id'), table_name='user', schema='vault')
    op.drop_table('user', schema='vault')
    # ### end Alembic commands ###
