"""Add status column to public_search_messages

Revision ID: db79c2138e02
Revises: 272f6d06eb69
Create Date: 2025-03-17 14:11:14.083468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db79c2138e02'
down_revision: Union[str, None] = '272f6d06eb69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    querystatus = postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'NEEDS_CLARIFICATION', 'IRRELEVANT', name='querystatus', create_type=True, schema='vault')
    querystatus.create(op.get_bind())
    
    # Add status column to public_search_messages table
    op.add_column('public_search_messages', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'NEEDS_CLARIFICATION', 'IRRELEVANT', name='querystatus', schema='vault'), nullable=False, comment='Status of the message (pending, completed, failed, etc.)', server_default='PENDING'), schema='vault')
    
    # Create index on status column
    op.create_index(op.f('ix_vault_public_search_messages_status'), 'public_search_messages', ['status'], unique=False, schema='vault')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index on status column
    op.drop_index(op.f('ix_vault_public_search_messages_status'), table_name='public_search_messages', schema='vault')
    
    # Drop status column
    op.drop_column('public_search_messages', 'status', schema='vault')
    
    # Drop enum type
    querystatus = postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'NEEDS_CLARIFICATION', 'IRRELEVANT', name='querystatus', schema='vault')
    querystatus.drop(op.get_bind())
    # ### end Alembic commands ###
