"""add_projects_class_for_workspaces

Revision ID: 2cfbb778ff67
Revises: f6d989a454d5
Create Date: 2025-01-15 13:29:30.304113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2cfbb778ff67'
down_revision: Union[str, None] = 'f6d989a454d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=False),
    sa.Column('practice_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidentiality', sa.Enum('PUBLIC', 'CONFIDENTIAL', name='confidentialitylevel'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('knowledge', sa.JSON(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('name', name='uq_project_name')
    )
    op.create_index('idx_project_created_by', 'projects', ['created_by'], unique=False)
    op.create_index('idx_project_modified', 'projects', ['modified_by', 'updated_at'], unique=False)
    op.create_index('idx_project_status_practice', 'projects', ['status', 'practice_area'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_practice_area'), 'projects', ['practice_area'], unique=False)
    op.create_index(op.f('ix_projects_start_date'), 'projects', ['start_date'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_updated_at'), 'projects', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_updated_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_start_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_practice_area'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index('idx_project_status_practice', table_name='projects')
    op.drop_index('idx_project_modified', table_name='projects')
    op.drop_index('idx_project_created_by', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
