"""Add Project and Notebook models

Revision ID: 37ddf95c14be
Revises: 2cfbb778ff67
Create Date: 2025-01-16 08:17:04.507377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '37ddf95c14be'
down_revision: Union[str, None] = '2cfbb778ff67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks',
    sa.Column('notebook_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('last_modified_content', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notebook_id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('idx_notebook_created', 'notebooks', ['created_by'], unique=False)
    op.create_index('idx_notebook_modified', 'notebooks', ['modified_by', 'updated_at'], unique=False)
    op.create_index('idx_notebook_project', 'notebooks', ['project_id'], unique=False)
    op.create_index(op.f('ix_notebooks_is_archived'), 'notebooks', ['is_archived'], unique=False)
    op.create_index(op.f('ix_notebooks_title'), 'notebooks', ['title'], unique=False)
    op.create_index(op.f('ix_notebooks_updated_at'), 'notebooks', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebooks_updated_at'), table_name='notebooks')
    op.drop_index(op.f('ix_notebooks_title'), table_name='notebooks')
    op.drop_index(op.f('ix_notebooks_is_archived'), table_name='notebooks')
    op.drop_index('idx_notebook_project', table_name='notebooks')
    op.drop_index('idx_notebook_modified', table_name='notebooks')
    op.drop_index('idx_notebook_created', table_name='notebooks')
    op.drop_table('notebooks')
    # ### end Alembic commands ###
