"""create_master_file_database

Revision ID: 4bc1c0460bf7
Revises: 9df3d4d190df
Create Date: 2025-01-23 20:51:30.829236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '4bc1c0460bf7'
down_revision: Union[str, None] = '9df3d4d190df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_file_database',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('ONEDRIVE', 'EMAIL', 'OUTLOOK', 'SHAREPOINT', 'TEAMS', 'MANUAL_UPLOAD', 'GENERATED', 'SCANNED', name='filesource'), nullable=False),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('directory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('import_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("file_attributes::jsonb ? 'document_type'", name='check_document_type'),
    sa.CheckConstraint("file_attributes::jsonb ? 'status'", name='check_file_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('idx_document_type', 'master_file_database', ['file_attributes'], unique=False, postgresql_using='gin')
    op.create_index('idx_file_status', 'master_file_database', ['file_attributes'], unique=False, postgresql_using='gin')
    op.create_index('idx_owner_source', 'master_file_database', ['owner_id', 'source'], unique=False)
    op.create_index('idx_owner_status', 'master_file_database', ['owner_id', 'file_attributes'], unique=False)
    op.create_index(op.f('ix_master_file_database_file_id'), 'master_file_database', ['file_id'], unique=False)
    op.create_index(op.f('ix_master_file_database_source'), 'master_file_database', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_file_database_source'), table_name='master_file_database')
    op.drop_index(op.f('ix_master_file_database_file_id'), table_name='master_file_database')
    op.drop_index('idx_owner_status', table_name='master_file_database')
    op.drop_index('idx_owner_source', table_name='master_file_database')
    op.drop_index('idx_file_status', table_name='master_file_database', postgresql_using='gin')
    op.drop_index('idx_document_type', table_name='master_file_database', postgresql_using='gin')
    op.drop_table('master_file_database')
    # ### end Alembic commands ###
