"""Create educational_knowledge table for storing VP education and training memory

Revision ID: 7bc9d3a9794a
Revises: b85bddb10ac6
Create Date: 2025-01-13 14:52:28.881754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '7bc9d3a9794a'
down_revision: Union[str, None] = 'b85bddb10ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('longterm_memory_educational_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vp_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('education_type', sa.Enum('LEGAL_HANDBOOK', 'PROFESSIONAL_GUIDELINES', 'BEST_PRACTICES', 'PROCEDURES', 'DOMAIN_PRINCIPLES', 'SPECIFIC_DETAILS', name='educationtype'), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vp_id'], ['virtual_paralegals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vp_id', 'education_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('longterm_memory_educational_knowledge')
    # ### end Alembic commands ###
