"""add integrations and credentials tables with oauth support

Revision ID: 9df3d4d190df
Revises: e1b872a1961a
Create Date: 2025-01-20 22:48:39.659653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '9df3d4d190df'
down_revision: Union[str, None] = 'e1b872a1961a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('integration_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('required_scopes', sa.JSON(), nullable=True),
    sa.Column('integration_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('integration_id')
    )
    op.create_index(op.f('ix_integrations_integration_id'), 'integrations', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integrations_name'), 'integrations', ['name'], unique=True)
    op.create_table('credentials',
    sa.Column('credential_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('integration_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credentials_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.integration_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('credential_id')
    )
    op.create_index(op.f('ix_credentials_credential_id'), 'credentials', ['credential_id'], unique=False)
    op.create_index(op.f('ix_credentials_integration_id'), 'credentials', ['integration_id'], unique=False)
    op.create_index(op.f('ix_credentials_user_id'), 'credentials', ['user_id'], unique=False)
    op.create_table('integration_abilities',
    sa.Column('integration_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.integration_id'], ),
    sa.PrimaryKeyConstraint('integration_id', 'ability_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integration_abilities')
    op.drop_index(op.f('ix_credentials_user_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_integration_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_credential_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_integrations_name'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_integration_id'), table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
