"""add reminder system to projects workspace

Revision ID: c604e5bbd4c3
Revises: 37ddf95c14be
Create Date: 2025-01-18 17:55:19.900804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c604e5bbd4c3'
down_revision: Union[str, None] = '37ddf95c14be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('reminder_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='reminderstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id')
    )
    op.create_index('idx_reminder_created_by', 'reminders', ['created_by'], unique=False)
    op.create_index('idx_reminder_due_date', 'reminders', ['due_date'], unique=False)
    op.create_index('idx_reminder_modified', 'reminders', ['modified_by', 'updated_at'], unique=False)
    op.create_index('idx_reminder_project', 'reminders', ['project_id'], unique=False)
    op.create_index('idx_reminder_status', 'reminders', ['status'], unique=False)
    op.create_index(op.f('ix_reminders_due_date'), 'reminders', ['due_date'], unique=False)
    op.create_index(op.f('ix_reminders_status'), 'reminders', ['status'], unique=False)
    op.create_index(op.f('ix_reminders_updated_at'), 'reminders', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_updated_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_status'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_due_date'), table_name='reminders')
    op.drop_index('idx_reminder_status', table_name='reminders')
    op.drop_index('idx_reminder_project', table_name='reminders')
    op.drop_index('idx_reminder_modified', table_name='reminders')
    op.drop_index('idx_reminder_due_date', table_name='reminders')
    op.drop_index('idx_reminder_created_by', table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
