"""Add VP profile pictures

Revision ID: c6ac18db7dc1
Revises: caae6e242947
Create Date: 2024-12-30 15:32:41.931052

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ac18db7dc1'
down_revision: Union[str, None] = 'caae6e242947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receive_email_abilities', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('task_management_abilities', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index('ix_task_management_abilities_techtree_id', table_name='task_management_abilities')
    op.create_index(op.f('ix_task_management_abilities_ability_id'), 'task_management_abilities', ['ability_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_management_abilities_ability_id'), table_name='task_management_abilities')
    op.create_index('ix_task_management_abilities_techtree_id', 'task_management_abilities', ['ability_id'], unique=False)
    op.alter_column('task_management_abilities', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('receive_email_abilities', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
