"""adding receive email ability

Revision ID: caae6e242947
Revises: e4460ccb9f2f
Create Date: 2024-12-16 12:52:21.897909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'caae6e242947'
down_revision: Union[str, None] = 'e4460ccb9f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receive_email_abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receive_email_abilities_ability_id'), 'receive_email_abilities', ['ability_id'], unique=False)
    op.create_index('ix_receive_email_abilities_operation_name', 'receive_email_abilities', ['operation_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receive_email_abilities_operation_name', table_name='receive_email_abilities')
    op.drop_index(op.f('ix_receive_email_abilities_ability_id'), table_name='receive_email_abilities')
    op.drop_table('receive_email_abilities')
    # ### end Alembic commands ###