"""Add profile picture to virtual paralegal

Revision ID: ec1dd6e757f7
Revises: 517ac52a4372
Create Date: 2024-12-30 17:35:27.958490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel import SQLModel

# revision identifiers, used by Alembic.
revision: str = 'ec1dd6e757f7'
down_revision: Union[str, None] = '517ac52a4372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_receive_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ability_receive_email_ability_id'), 'ability_receive_email', ['ability_id'], unique=False)
    op.create_index('ix_ability_receive_email_operation_name', 'ability_receive_email', ['operation_name'], unique=False)
    op.drop_index('ix_receive_email_abilities_ability_id', table_name='receive_email_abilities')
    op.drop_index('ix_receive_email_abilities_operation_name', table_name='receive_email_abilities')
    op.drop_table('receive_email_abilities')
    op.add_column('virtual_paralegals', sa.Column('profile_picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'virtual_paralegals', 'vp_profile_pictures', ['profile_picture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtual_paralegals', type_='foreignkey')
    op.drop_column('virtual_paralegals', 'profile_picture_id')
    op.create_table('receive_email_abilities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ability_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operation_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('workflow_steps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], name='receive_email_abilities_ability_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='receive_email_abilities_pkey')
    )
    op.create_index('ix_receive_email_abilities_operation_name', 'receive_email_abilities', ['operation_name'], unique=False)
    op.create_index('ix_receive_email_abilities_ability_id', 'receive_email_abilities', ['ability_id'], unique=False)
    op.drop_index('ix_ability_receive_email_operation_name', table_name='ability_receive_email')
    op.drop_index(op.f('ix_ability_receive_email_ability_id'), table_name='ability_receive_email')
    op.drop_table('ability_receive_email')
    # ### end Alembic commands ###