"""add_behaviour_vps_table

Revision ID: fcab40cf5e14
Revises: 26f8a56ea342
Create Date: 2025-01-12 11:17:04.751563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'fcab40cf5e14'
down_revision: Union[str, None] = '26f8a56ea342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaviour_vps',
    sa.Column('vp_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('behaviour_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['behaviour_id'], ['behaviours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vp_id'], ['virtual_paralegals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vp_id', 'behaviour_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('behaviour_vps')
    # ### end Alembic commands ###
