"""create_tech_tree_table

Revision ID: 1664174135e3
Revises: 9dd2bf26ffd0
Create Date: 2024-12-11 13:48:16.568410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON

# revision identifiers, used by Alembic.
revision: str = '1664174135e3'
down_revision: Union[str, None] = '9dd2bf26ffd0'  # Point to the tech_tree_progress migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),  # Changed from sqlmodel.sql.sqltypes.AutoString
    sa.Column('description', sa.String(), nullable=False),  # Changed from sqlmodel.sql.sqltypes.AutoString
    sa.Column('structure', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_trees')
    # ### end Alembic commands ###