"""add_longterm_memory_self_identity_table

Revision ID: 26f8a56ea342
Revises: e6b51bab5a28
Create Date: 2025-01-10 17:12:43.472159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = '26f8a56ea342'
down_revision: Union[str, None] = 'e6b51bab5a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('longterm_memory_self_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vp_id', UUID(), nullable=False),  # Changed to UUID type
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vp_id'], ['virtual_paralegals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('longterm_memory_self_identity')
    # ### end Alembic commands ###

