"""Create vp profile pictures table properly

Revision ID: 517ac52a4372
Revises: c6ac18db7dc1
Create Date: 2024-12-30 15:37:31.738057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '517ac52a4372'
down_revision: Union[str, None] = 'c6ac18db7dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vp_profile_pictures',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('image_url', sa.String(), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vp_profile_pictures_display_order'), 'vp_profile_pictures', ['display_order'], unique=False)
    op.create_index(op.f('ix_vp_profile_pictures_name'), 'vp_profile_pictures', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vp_profile_pictures_name'), table_name='vp_profile_pictures')
    op.drop_index(op.f('ix_vp_profile_pictures_display_order'), table_name='vp_profile_pictures')
    op.drop_table('vp_profile_pictures')
    # ### end Alembic commands ###