"""add_clients_module_with_relationships_and_enums

Revision ID: 5b3287a01b77
Revises: 19bd875f47ff
Create Date: 2025-01-19 17:43:06.421795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '5b3287a01b77'
down_revision: Union[str, None] = '19bd875f47ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_entity_type', sa.Enum('INDIVIDUAL', 'SOLE_PROPRIETORSHIP', 'PARTNERSHIP', 'LIMITED_PARTNERSHIP', 'CORPORATION', 'LLC', 'LLP', 'NONPROFIT', 'TRUST', 'FOUNDATION', 'ASSOCIATION', 'COOPERATIVE', 'JOINT_VENTURE', 'STATUTORY_COMPANY', 'GOVERNMENT_ENTITY', 'EDUCATIONAL_INSTITUTION', 'RELIGIOUS_ORGANIZATION', 'CHARITY', 'ESTATE', 'FOREIGN_ENTITY', 'SPECIAL_PURPOSE_VEHICLE', 'MUTUAL_FUND', 'HEDGE_FUND', 'PENSION_FUND', name='legalentitytype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='clientstatus'), nullable=False),
    sa.Column('domicile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_join_date', sa.DateTime(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index('idx_client_created', 'clients', ['created_by'], unique=False)
    op.create_index('idx_client_entity_type', 'clients', ['legal_entity_type'], unique=False)
    op.create_index('idx_client_join_date', 'clients', ['client_join_date'], unique=False)
    op.create_index('idx_client_modified', 'clients', ['modified_by', 'updated_at'], unique=False)
    op.create_index('idx_client_name', 'clients', ['name'], unique=False)
    op.create_index('idx_client_status', 'clients', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_client_status', table_name='clients')
    op.drop_index('idx_client_name', table_name='clients')
    op.drop_index('idx_client_modified', table_name='clients')
    op.drop_index('idx_client_join_date', table_name='clients')
    op.drop_index('idx_client_entity_type', table_name='clients')
    op.drop_index('idx_client_created', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
