"""Add conversational history to longterm memory

Revision ID: 895ec5a4d557
Revises: 7bc9d3a9794a
Create Date: 2025-01-13 15:21:51.096074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '895ec5a4d557'
down_revision: Union[str, None] = '7bc9d3a9794a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('longterm_memory_conversational_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vp_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vp_id'], ['virtual_paralegals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('longterm_memory_conversational_history')
    # ### end Alembic commands ###
