"""add_longterm_memory_global_knowledge_table_with_knowledge_types

Revision ID: b85bddb10ac6
Revises: fcab40cf5e14
Create Date: 2025-01-12 13:35:09.628658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'b85bddb10ac6'
down_revision: Union[str, None] = 'fcab40cf5e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('longterm_memory_global_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vp_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('knowledge_type', sa.Enum('SYSTEM_STATS', 'USER_SPECIALIZATIONS', 'ORGANIZATIONAL_POLICIES', 'PROJECT_OVERVIEW', 'INTEGRATION_ACCESS', name='knowledgetype'), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vp_id'], ['virtual_paralegals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vp_id', 'knowledge_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('longterm_memory_global_knowledge')
    # ### end Alembic commands ###
