"""Add task management ability table

Revision ID: cc37daa79a8e
Revises: 1664174135e3
Create Date: 2024-12-11 22:44:47.528857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc37daa79a8e'
down_revision: Union[str, None] = '1664174135e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_management_abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('techtree_id', sa.Integer(), nullable=False),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['techtree_id'], ['tech_trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_management_abilities_techtree_id'), 'task_management_abilities', ['techtree_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_management_abilities_techtree_id'), table_name='task_management_abilities')
    op.drop_table('task_management_abilities')
    # ### end Alembic commands ###
