"""add contact management system with client and project relationships

Revision ID: e1b872a1961a
Revises: 44024615a64b
Create Date: 2025-01-20 11:41:48.023734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'e1b872a1961a'
down_revision: Union[str, None] = '44024615a64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contact_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_type', sa.Enum('INTERNAL', 'CLIENT', 'EXTERNAL', name='contacttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='contactstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index('idx_contact_created', 'contacts', ['created_by'], unique=False)
    op.create_index('idx_contact_email', 'contacts', ['email'], unique=False)
    op.create_index('idx_contact_modified', 'contacts', ['modified_by', 'updated_at'], unique=False)
    op.create_index('idx_contact_name', 'contacts', ['first_name', 'last_name'], unique=False)
    op.create_index('idx_contact_status', 'contacts', ['status'], unique=False)
    op.create_index('idx_contact_type', 'contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_table('contact_clients',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'SECONDARY', 'LEGAL', 'TECHNICAL', 'BILLING', 'ADMINISTRATIVE', 'OTHER', name='contactrole'), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('contact_id', 'client_id')
    )
    op.create_index('idx_contact_client_created', 'contact_clients', ['created_by'], unique=False)
    op.create_index('idx_contact_client_role', 'contact_clients', ['role'], unique=False)
    op.create_table('contact_projects',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('LEAD', 'ATTORNEY', 'PARALEGAL', 'CONSULTANT', 'EXPERT', 'REVIEWER', 'SUPPORT', 'OTHER', name='projectrole'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'project_id')
    )
    op.create_index('idx_contact_project_created', 'contact_projects', ['created_by'], unique=False)
    op.create_index('idx_contact_project_role', 'contact_projects', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contact_project_role', table_name='contact_projects')
    op.drop_index('idx_contact_project_created', table_name='contact_projects')
    op.drop_table('contact_projects')
    op.drop_index('idx_contact_client_role', table_name='contact_clients')
    op.drop_index('idx_contact_client_created', table_name='contact_clients')
    op.drop_table('contact_clients')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index('idx_contact_type', table_name='contacts')
    op.drop_index('idx_contact_status', table_name='contacts')
    op.drop_index('idx_contact_name', table_name='contacts')
    op.drop_index('idx_contact_modified', table_name='contacts')
    op.drop_index('idx_contact_email', table_name='contacts')
    op.drop_index('idx_contact_created', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
