"""add behaviour and ability_behaviour tables

Revision ID: e6b51bab5a28
Revises: ec1dd6e757f7
Create Date: 2025-01-09 21:53:25.886966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import AutoString
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e6b51bab5a28'
down_revision: Union[str, None] = 'ec1dd6e757f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaviours',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DEPRECATED', name='behaviourstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behaviours_name'), 'behaviours', ['name'], unique=True)
    op.create_table('ability_behaviours',
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('behaviour_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['behaviour_id'], ['behaviours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ability_id', 'behaviour_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ability_behaviours')
    op.drop_index(op.f('ix_behaviours_name'), table_name='behaviours')
    op.drop_table('behaviours')
    # ### end Alembic commands ###
